const String supabaseURL = "https://xhjyjqkgebzcuoizrrqv.supabase.co";
const String supabaseAnonKey =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoanlqcWtnZWJ6Y3VvaXpycnF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MzE1NDMsImV4cCI6MjA3MzIwNzU0M30.cr1ZcBrEdlQffIUgBaTZCLmyz-6b_MblIk0C0pq3el4";
